
#most of these are fully or partly generated by ai 
#for diagnostics only 


def plot_alpha_beta_hit_diagnostics(n_each=6):

    # Only select nodes for which alpha was actually estimable
    valid_alpha_nodes = np.where(np.isfinite(alpha))[0]

    sorted_valid = valid_alpha_nodes[np.argsort(alpha[valid_alpha_nodes])]

    most_negative = sorted_valid[:n_each]
    most_positive = sorted_valid[-n_each:][::-1]
    selected_nodes = np.concatenate([most_negative, most_positive])

    mlmc_levels = np.arange(1, L + 1)
    step_levels = mlmc_levels + MLMC_LEVEL_OFFSET
    n_nodes = len(selected_nodes)

    fig, axes = plt.subplots(
        n_nodes, 3,
        figsize=(16, 2.8*n_nodes),
        sharex="col"
    )
    axes = np.atleast_2d(axes)

    for row, node in enumerate(selected_nodes):

        # ---------------- ALPHA REGRESSION ----------------

        mean_diff = np.abs(del1[node, 1:L+1])

        # Same mask used when calculating alpha
        mean_mask = mean_diff > 1e-15

        used_mean_levels = mlmc_levels[mean_mask]
        used_mean_steps = step_levels[mean_mask]
        used_mean = mean_diff[mean_mask]
        log_mean = np.log2(used_mean)

        if np.sum(mean_mask) >= 2:
            pa = np.polyfit(used_mean_levels, log_mean, 1)

            # Plot fitted line only over the levels actually used
            fitted_mean = np.polyval(pa, used_mean_levels)

            axes[row, 0].plot(
                used_mean_steps, log_mean,
                "o", markersize=4
            )
            axes[row, 0].plot(
                used_mean_steps, fitted_mean,
                "-", linewidth=1
            )

        axes[row, 0].set_title(
            rf"Node {node}, position {nodes_array[node]} | "
            rf"$\alpha={alpha[node]:.3f}$"
        )
        axes[row, 0].set_ylabel(
            r"$\log_2|\mathbb{E}[P_\ell-P_{\ell-1}]|$"
        )

        # ---------------- BETA REGRESSION ----------------

        variance = np.abs(var1[node, 1:L+1])

        # Same mask used when calculating beta
        variance_mask = variance > 1e-15

        used_var_levels = mlmc_levels[variance_mask]
        used_var_steps = step_levels[variance_mask]
        used_variance = variance[variance_mask]
        log_variance = np.log2(used_variance)

        if np.sum(variance_mask) >= 2:
            pb = np.polyfit(used_var_levels, log_variance, 1)

            fitted_variance = np.polyval(pb, used_var_levels)

            axes[row, 1].plot(
                used_var_steps, log_variance,
                "o", markersize=4
            )
            axes[row, 1].plot(
                used_var_steps, fitted_variance,
                "-", linewidth=1
            )

        axes[row, 1].set_title(
            rf"Node {node}, position {nodes_array[node]} | "
            rf"$\beta={beta[node]:.3f}$"
        )
        axes[row, 1].set_ylabel(
            r"$\log_2(\mathrm{Var}[P_\ell-P_{\ell-1}])$"
        )

        # ---------------- FINE + COARSE HIT RATE ----------------

        fine = fine_hit_rates[node, 1:L+1]
        coarse = coarse_hit_rates[node, 1:L+1]

        axes[row, 2].plot(
            step_levels, fine,
            "o-", linewidth=1, markersize=4,
            label="Fine"
        )
        axes[row, 2].plot(
            step_levels, coarse,
            "o-", linewidth=1, markersize=4,
            label="Coarse"
        )

        ymin = min(np.min(fine), np.min(coarse))
        ymax = max(np.max(fine), np.max(coarse))

        padding = (
            0.05*(ymax-ymin)
            if ymax > ymin
            else max(1/N, 0.01*ymax)
        )

        axes[row, 2].set_ylim(
            max(0, ymin-padding),
            ymax+padding
        )

        axes[row, 2].set_title(
            f"Node {node}, position {nodes_array[node]} | "
            "Fine / coarse hit rate"
        )
        axes[row, 2].set_ylabel("Hit rate")

    # Legend only once
    axes[0, 2].legend(fontsize=8)

    for col in range(3):
        axes[-1, col].set_xlabel(r"Step level")

    for ax in axes.flat:
        ax.set_xticks(step_levels)

    fig.suptitle(
        "MLMC convergence regressions and hit rates at extreme-alpha nodes",
        fontsize=14
    )

    plt.tight_layout(rect=[0, 0, 1, 0.99])

    save_path = os.path.join(
        file_path,
        f"alpha_beta_hit_diagnostics_nodes_{n_nodes}_"
        f"L_{L}_offset_{MLMC_LEVEL_OFFSET}_N_{N}.png"
    )

    fig.savefig(save_path, dpi=300)
    print(f"Saved to: {save_path}")

    plt.show()

return selected_nodes

def plot_alpha_beta_map():
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    sc_alpha = axes[0].scatter(nodes_array[:, 0],nodes_array[:, 1],c=alpha)
    axes[0].set_title(r"$\alpha$")
    axes[0].set_xlabel("x")
    axes[0].set_ylabel("y")
    axes[0].set_aspect("equal")
    fig.colorbar(sc_alpha, ax=axes[0], label=r"$\alpha$")

    sc_beta = axes[1].scatter(nodes_array[:, 0],nodes_array[:, 1],c=beta)
    axes[1].set_title(r"$\beta$")
    axes[1].set_xlabel("x")
    axes[1].set_ylabel("y")
    axes[1].set_aspect("equal")
    fig.colorbar(sc_beta, ax=axes[1], label=r"$\beta$")

    fig.suptitle(f"{title_seg} MLMC Test: Convergence Rates (M={N_conv_test})")
    plt.tight_layout()
    ab_save_path = os.path.join(file_path,
    f"alpha_beta_map_{dose_method}"
    f"_maxlvl_{L_conv_test}"
    f"_offset_{MLMC_LEVEL_OFFSET}"
    f"_mcsims_{N_conv_test}.png"
    )

    plt.savefig(ab_save_path, dpi=300, bbox_inches="tight")
    plt.show()

def plot_moments_2_4():
    for mlmc_level in [L]:
        m2 = cent2[:, mlmc_level]
        m4 = cent4[:, mlmc_level]
        ratio = np.full(num_q, np.nan)
        mask = m2 > 0
        ratio[mask] = (m4[mask]/ m2[mask])

        fig, axes = plt.subplots(1,3,figsize=(17, 5),sharex=True,sharey=True)
        sc0 = axes[0].scatter(nodes_array[:, 0],nodes_array[:, 1],c=m2)
        axes[0].set_title(r"$\mathbb{E}[(Y_\ell-\mathbb{E}(Y_\ell))^2]^2$")
        fig.colorbar(sc0,ax=axes[0])
        sc1 = axes[1].scatter(nodes_array[:, 0],nodes_array[:, 1],c=m4)
        axes[1].set_title(r"$\mathbb{E}[(Y_\ell - \mathbb{E}(Y_\ell))^4]$")
        fig.colorbar(sc1,ax=axes[1])

        sc2 = axes[2].scatter(nodes_array[:, 0],nodes_array[:, 1],c=ratio)
        axes[2].set_title(r"$\mathbb{E}[(Y_\ell - \mathbb{E}(Y_\ell))^4]/\mathbb{E}[(Y_\ell-\mathbb{E}(Y_\ell))^2]^2$")
        fig.colorbar(sc2,ax=axes[2])
        for ax in axes:
            ax.set_xlabel("x")
            ax.set_aspect("equal")
        axes[0].set_ylabel("y")
        fig.suptitle(rf"MLMC Moments, $h_\ell=T \cdot 2^{{-{mlmc_level+MLMC_LEVEL_OFFSET}}}$, (N={N})")
        plt.tight_layout()
        plt.show()

def plot_fine_payoff():
    mc_level = 9 #for fair comparison
    print(f"Plotting fine payoff from mlmc test with {N} samples at step size level {mc_level}")
    mlmc_level = mc_level - MLMC_LEVEL_OFFSET
    fine_payoff = del2[:, mlmc_level]
    plt.figure(figsize=(6, 5))
    sc = plt.scatter(nodes_array[:, 0],nodes_array[:, 1],c=fine_payoff)
    plt.colorbar(sc, label=r"$\mathbb{E}[P_\ell]$")
    plt.xlabel("x")
    plt.ylabel("y")
    plt.title(rf"{title_seg} MLMC Test: Fine Payoff, $h_\ell = T \cdot {base}^{{-{mc_level}}}$ (M={N_conv_test})")
    plt.gca().set_aspect("equal")

    print("Maximum fine payoff:", np.max(fine_payoff))
    print("Node of max payoff:", nodes_array[np.argmax(fine_payoff)])
    fine_P_save_path = os.path.join(file_path, f"fine_payoff_mlmc_test_{dose_method}_maxlvl_{L_conv_test}_offset_{MLMC_LEVEL_OFFSET}_mcsims_{N_conv_test}.png")
    plt.savefig(fine_P_save_path, dpi=300)
    plt.show()

def plot_kurtosis_heatmap(log_kurt=False):
    print(f"Plotting kurtosis heatmap for mlmc estimator from mlmc levels 1 to {L}...")
    kurt_all = kur1[:, 1:]
    if log_kurt:
        kurt_plot = np.log10(1 + np.maximum(kurt_all, 0)) #make the kurts all >=0
        vmin = np.min(kurt_plot) #colour bar endpoints
        vmax = np.max(kurt_plot)
    else:
        kurt_plot=kurt_all
        vmin = np.min(kurt_all) 
        vmax = np.max(kurt_all)
    #Create the grid for heatmaps 
    ncols = 3
    nrows = int(np.ceil(L / ncols)) #plot all the levels
    fig, axes = plt.subplots(nrows,ncols,figsize=(5 * ncols, 4 * nrows))

    axes = np.atleast_1d(axes).ravel()
    for idx, l in enumerate(range(1, L + 1)):
        #Create scatter over the nodes array for kurt values 
        sc = axes[idx].scatter(nodes_array[:, 0],nodes_array[:, 1],c=kurt_plot[:, l - 1],vmin=vmin,vmax=vmax)
        axes[idx].set_title(rf"$\ell = {l}: h_\ell = T \cdot {base}^{{-{MLMC_LEVEL_OFFSET + l}}}$")
        axes[idx].set_aspect("equal")
    #Remove any empty subplot slots
    for idx in range(L, len(axes)):
        fig.delaxes(axes[idx])
    #Shared colour bar
    label = "log10(1 + kurtosis)" if log_kurt else r"$Y_\ell$ Kurtosis"
    fig.colorbar(sc,ax=axes[:L].tolist(),label=label)
    fig.suptitle(f"{title_seg} MLMC Test:{'Log' if log_kurt else ''} Kurtosis Heatmap (M={N_conv_test})")
    kurt_save_path = os.path.join(file_path, f"{'log_' if log_kurt else ''}kurtosis_map_{dose_method}_maxlvl_{L_conv_test}_offset_{MLMC_LEVEL_OFFSET}_mcsims_{N_conv_test}.png")
    plt.savefig(kurt_save_path, dpi=300)
    plt.show()